
'use client';

import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import { ScribeSigil } from '../icons';
import { InfidelityRadarOutput } from '@/ai/flows/infidelity-radar-agent';
import { Separator } from '../ui/separator';

interface DossierViewerProps {
  analysis: InfidelityRadarOutput;
}

/**
 * A Micro-App to display a formal, stylized intelligence dossier.
 * Fulfills the "Dossier Export" scripture by presenting consecrated evidence.
 */
export function DossierViewer({ analysis }: DossierViewerProps) {
  const caseId = `CASE-${new Date().getTime()}`;

  return (
    <div className="h-full w-full flex flex-col bg-slate-900 text-slate-300 font-mono">
      <header className="p-4 bg-slate-800/50 border-b border-slate-700 flex justify-between items-center">
        <div>
          <h2 className="text-lg font-bold tracking-widest text-red-400">AEGIS PROTOCOL - DOSSIER</h2>
          <p className="text-xs text-slate-400">CLASSIFIED // SOVEREIGN EYES ONLY</p>
        </div>
        <ScribeSigil className="h-10 w-10 text-red-400/70" />
      </header>

      <ScrollArea className="flex-grow">
        <div className="p-6 space-y-6">
          {/* Header Section */}
          <div className="grid grid-cols-3 gap-4 text-sm">
            <div>
              <p className="text-slate-500">CASE ID:</p>
              <p className="font-bold">{caseId}</p>
            </div>
            <div>
              <p className="text-slate-500">DATE:</p>
              <p className="font-bold">{new Date().toUTCString()}</p>
            </div>
            <div>
              <p className="text-slate-500">VERIFIED BY:</p>
              <p className="font-bold">AEGIS-PRIME</p>
            </div>
          </div>
          
          <Separator className='bg-slate-700' />

          {/* Analysis Section */}
          <div>
            <h3 className="text-base font-bold tracking-wider text-red-400 border-b border-red-400/30 pb-1 mb-3">1. LIKELIHOOD ASSESSMENT</h3>
            <div className='flex items-baseline gap-4'>
                <p className='text-6xl font-bold text-slate-100'>{analysis.likelihood}%</p>
                <p className='text-slate-400'>Likelihood of Concealed Behavior</p>
            </div>
            <blockquote className="mt-4 border-l-2 border-slate-600 pl-4 text-slate-400 italic">
              {analysis.analysis}
            </blockquote>
          </div>
          
          {/* Evidence Section */}
          <div>
             <h3 className="text-base font-bold tracking-wider text-red-400 border-b border-red-400/30 pb-1 mb-3">2. SUSPICIOUS PATTERNS (METADATA)</h3>
             <ul className="list-decimal list-inside space-y-2 text-slate-300">
                {analysis.suspiciousPatterns.map((pattern, index) => (
                    <li key={index}>
                        <span className="font-semibold">Pattern {index+1}:</span> {pattern}
                    </li>
                ))}
             </ul>
          </div>
          
           {/* Decoy Section */}
          <div>
            <h3 className="text-base font-bold tracking-wider text-red-400 border-b border-red-400/30 pb-1 mb-3">3. DECOY MESSAGE TRANSCRIPT</h3>
            <div className="p-4 bg-slate-800/50 rounded-md border border-slate-700">
                <p className="text-slate-400 text-xs mb-2">Deployed by Seduction Agent™:</p>
                <p className="font-semibold text-slate-200">"{analysis.decoyMessage}"</p>
            </div>
          </div>
          
          <Separator className='bg-slate-700' />

          {/* Footer */}
          <div className="text-center text-xs text-slate-500">
            <p>This document was generated by ΛΞVON OS under the Vow of Sovereignty Protocol.</p>
            <p>The system witnessed it. The hash does not lie.</p>
            <p>END OF REPORT</p>
          </div>

        </div>
      </ScrollArea>
    </div>
  );
}
